# Generated by Django 3.1.5 on 2021-02-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_motive', models.CharField(choices=[('general_enquiry', 'GENERAL ENQUIRY'), ('product_technical_assistance', 'PRODUCT TECHNICAL ASSISTANCE'), ('product_suggestion', 'PRODUCT SUGGESTION'), ('general_feedback', 'GENERAL FEEDBACK')], default='general_enquiry', max_length=120)),
                ('product_sku', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=90)),
                ('main_message', models.CharField(max_length=3000)),
                ('responded', models.BooleanField(default=False)),
            ],
        ),
    ]
