# Generated by Django 3.1.5 on 2021-02-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20210220_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='main_message',
            field=models.TextField(max_length=3000),
        ),
    ]
