# Generated by Django 3.1.5 on 2021-02-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210225_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video',
        ),
        migrations.RemoveField(
            model_name='product',
            name='video_url',
        ),
    ]
